# Generated by Django 6.0.4 on 2026-05-06 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('users', '0002_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to='levels.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_levels', to='users.user')),
            ],
            options={
                'unique_together': {('student', 'level')},
            },
        ),
    ]
